[project]
name = "udocker"
version = "attr: udocker.__version__"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-ra --cov-report term --cov=udocker"
testpaths = [
    "test/units",
]
