config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Acc:
    repos:
      this_repo:
        commands:
        - git rev-parse --is-inside-work-tree
        container: qc.acc_lumpy-orange-bird
  QC.Doc:
    repos:
      this_repo:
        commands:
        - mdl .
        container: qc.doc_freaky-lemon-crab
  QC.Lic:
    repos:
      this_repo:
        commands:
        - licensee detect . --json
        container: qc.lic_gimpy-cornflower-iguana
  QC.Met:
    repos:
      this_repo:
        commands:
        - checkCitable
        container: qc.met_jumpy-burgundy-fossa
      this_repo__2:
        commands:
        - cat codemeta.json
        container: qc.met_snippy-apricot-worm
  QC.Sec:
    repos:
      this_repo:
        commands:
        - bandit -f json --quiet  --confidence-level medium --recursive .
        container: qc.sec_shaggy-russet-budgerigar
  QC.Sty:
    repos:
      this_repo:
        commands:
        - tox -c tox.ini -e pylint
        container: qc.sty_wimpy-eggplant-wrasse
  QC.Uni:
    repos:
      this_repo:
        commands:
        - tox -c tox.ini -e unit_tests
        container: qc.uni_beady-copper-capuchin
  QC.Ver:
    repos:
      this_repo:
        commands:
        - get_git_tags.py
        container: qc.ver_jumpy-azure-fousek
timeout: 1800
