services:
  qc.acc_udocker:
    build:
      context: ./dockercicd
      dockerfile: Dockerfile_git
      args:
        UID: "$(id -u)"
        GID: "$(id -g)"
        UNAME: jenkis
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
